FROM node:24 

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN export $(grep -v '^#' .env | xargs) && npx prisma generate

#RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start:dev", "--", "--legacy-watch" ]